name: Almeida Ticket Monitor

on:
  schedule:
    # Runs every 5 minutes  (GitHub's minimum is 5 mins)
    - cron: "*/5 * * * *"
  workflow_dispatch:   # lets you trigger it manually from GitHub too

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      # 1. Check out the repo so we can read/write last_hash.txt
      - name: Checkout repo
        uses: actions/checkout@v4

      # 2. Set up Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      # 3. Install dependencies
      - name: Install dependencies
        run: pip install requests

      # 4. Run the monitor script
      - name: Run ticket check
        env:
          NOTIFY_EMAIL:    ${{ secrets.NOTIFY_EMAIL }}
          NOTIFY_PASSWORD: ${{ secrets.NOTIFY_PASSWORD }}
        run: python check_tickets.py

      # 5. Save updated hash back to the repo so next run can compare
      - name: Save hash file
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add last_hash.txt
          git diff --staged --quiet || git commit -m "chore: update page hash"
          git push
